name: x86_64 and i686 release builds

on:
  push:
    tags:
      - "v*-rev*"

jobs:
  split-tag:
    runs-on: ubuntu-latest
    outputs:
      gcc-version: ${{ steps.get-gcc-version.outputs.version }}
      mingw-rev: ${{ steps.get-mingw-revision.outputs.rev }}
    steps:
      - id: get-gcc-version
        run: echo "::set-output name=version::$(echo ${{ github.ref_name }} | cut -d- -f1 | cut -c2-)"
      - id: get-mingw-revision
        run: echo "::set-output name=rev::$(echo ${{ github.ref_name }} | cut -d- -f2 | cut -c4-)"

  build:
    needs: split-tag
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686]
        threads: [posix, win32]
        exceptions: [sjlj, seh, dwarf]
        exclude:
          - arch: x86_64
            exceptions: dwarf
          - arch: i686
            exceptions: seh

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'niXman/mingw-builds'
        ref: 'develop'

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build
      shell: msys2 {0}
      run: ./build --mode=gcc-${{ needs.split-tag.outputs.gcc-version }} --buildroot=buildroot --jobs=4 --rev=${{ needs.split-tag.outputs.mingw-rev }} --rt-version=v9 --threads=${{ matrix.threads }} --exceptions=${{ matrix.exceptions }} --arch=${{ matrix.arch }} --bin-compress --enable-languages=c,c++

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ./buildroot/archives/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        path: ./

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.7z"
